# -*- coding: utf-8 -*-
"""PCD_Assignment01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gVJjdT5hnmiwZDhSTVK1M2kkscK7wgTb

1. import libraries:
"""

import numpy as np
from PIL import Image
from google.colab import files
import os
import matplotlib.pyplot as plt

"""2. upload and display original image:


"""

print("Upload the image you want to downsample: ")
uploaded = files.upload()

for fn in uploaded.keys():
  print(f'Uploaded file "{fn}" with length {len(uploaded[fn])} bytes'.format(name=fn, length=len(uploaded[fn])))

"""3. convert to numpy array:"""

def get_img_array(img_path):
    img = Image.open(img_path).convert('RGB')
    return np.array(img, dtype=np.float32)

"""4. downscaling:"""

def max_downscale(img_array, down_factor):
    h, w, c = img_array.shape
    new_h = h // down_factor
    new_w = w // down_factor

    max_downscaled = np.zeros((new_h, new_w, c), dtype=np.float32)

    for i in range(new_h):
        for j in range(new_w):
            # Define block boundaries
            h_start, h_end = i * down_factor, (i + 1) * down_factor
            w_start, w_end = j * down_factor, (j + 1) * down_factor

            # Extract the block
            block = img_array[h_start:h_end, w_start:w_end, :]

            # Calculate max for each channel
            for channel in range(c):
                max_downscaled[i, j, channel] = np.max(block[:, :, channel])

    return max_downscaled

def mean_downscale(img_array, down_factor):
    h, w, c = img_array.shape
    new_h = h // down_factor
    new_w = w // down_factor

    mean_downscaled = np.zeros((new_h, new_w, c), dtype=np.float32)

    for i in range(new_h):
        for j in range(new_w):
            # Define block boundaries
            h_start, h_end = i * down_factor, (i + 1) * down_factor
            w_start, w_end = j * down_factor, (j + 1) * down_factor

            # Extract the block
            block = img_array[h_start:h_end, w_start:w_end, :]

            # Calculate mean for each channel
            for channel in range(c):
                mean_downscaled[i, j, channel] = np.mean(block[:, :, channel])

    return mean_downscaled

def min_downscale(img_array, down_factor):
    h, w, c = img_array.shape
    new_h = h // down_factor
    new_w = w // down_factor

    min_downscaled = np.zeros((new_h, new_w, c), dtype=np.float32)

    for i in range(new_h):
        for j in range(new_w):
            # Define block boundaries
            h_start, h_end = i * down_factor, (i + 1) * down_factor
            w_start, w_end = j * down_factor, (j + 1) * down_factor

            # Extract the block
            block = img_array[h_start:h_end, w_start:w_end, :]

            # Calculate max for each channel
            for channel in range(c):
                min_downscaled[i, j, channel] = np.min(block[:, :, channel])

    return min_downscaled

"""5. upscaling:"""

def nn_upscale(img_array, up_factor):
    h, w, c = img_array.shape
    new_h = h * up_factor
    new_w = w * up_factor

    nn_upscaled = np.zeros((new_h, new_w, c), dtype=np.float32)

  # Find the nearest neighbor's pixel value
    for i in range(new_h):
        for j in range(new_w):
            orig_i = i // up_factor
            orig_j = j // up_factor

            # Assign the pixel value from the original image
            nn_upscaled[i, j, :] = img_array[orig_i, orig_j, :]

    return nn_upscaled

def bilinear_upscale(img_array, up_factor):
    h, w, c = img_array.shape
    new_h = h * up_factor
    new_w = w * up_factor

    bilinear_upscaled = np.zeros((new_h, new_w, c), dtype=np.float32)

    for i in range(new_h):
        for j in range(new_w):
            # Map output coordinates to input coordinates (floating point)
            orig_i = i / up_factor
            orig_j = j / up_factor

            # Find the coordinates of the 4 surrounding pixels
            i_low = int(np.floor(orig_i))
            i_high = min(i_low + 1, h - 1)
            j_low = int(np.floor(orig_j))
            j_high = min(j_low + 1, w - 1)

            # Calculate the fractional weights
            di = orig_i - i_low
            dj = orig_j - j_low

            # Perform bilinear interpolation for each channel
            for channel in range(c):
                # Get values of the 4 neighbors
                v1 = img_array[i_low, j_low, channel]
                v2 = img_array[i_high, j_low, channel]
                v3 = img_array[i_low, j_high, channel]
                v4 = img_array[i_high, j_high, channel]

                # Linear interpolation along i then j
                val = (v1 * (1 - di) * (1 - dj) +
                       v2 * di * (1 - dj) +
                       v3 * (1 - di) * dj +
                       v4 * di * dj)

                bilinear_upscaled[i, j, channel] = val

    return bilinear_upscaled

def bicubic_upscale(img_array, up_factor):
    h, w, c = img_array.shape
    new_h = h * up_factor
    new_w = w * up_factor
    def get_weights(x):
        a = -0.5
        x = np.abs(x)
        w = np.zeros_like(x)
        mask1 = x <= 1
        mask2 = (x > 1) & (x < 2)
        w[mask1] = (a + 2) * (x[mask1]**3) - (a + 3) * (x[mask1]**2) + 1
        w[mask2] = a * (x[mask2]**3) - 5 * a * (x[mask2]**2) + 8 * a * x[mask2] - 4 * a
        return w

    x_out = np.arange(new_w) / up_factor
    y_out = np.arange(new_h) / up_factor

    # Indices of the 4x4 neighborhood
    x_low = np.floor(x_out).astype(int)
    y_low = np.floor(y_out).astype(int)

    # Precompute weights
    wx = np.stack([get_weights(x_out - (x_low + i)) for i in range(-1, 3)], axis=0)
    wy = np.stack([get_weights(y_out - (y_low + i)) for i in range(-1, 3)], axis=0)

    # Output array
    bicubic_upscaled = np.zeros((new_h, new_w, c), dtype=np.float32)

    for channel in range(c):
        for m in range(4):
            for n in range(4):
                # Neighbor coordinates
                curr_y = np.clip(y_low + m - 1, 0, h - 1)
                curr_x = np.clip(x_low + n - 1, 0, w - 1)

                # Sample from original image
                samples = img_array[curr_y[:, None], curr_x, channel]

                # Apply weights
                bicubic_upscaled[:, :, channel] += samples * wy[m][:, None] * wx[n]

    bicubc_upscaled = np.clip(bicubic_upscaled, 0, 255)
    return bicubc_upscaled

"""Input factors, display, and download resulting images:"""

def save_and_download(img_array, filename):
    rescaled = np.clip(img_array, 0, 255).astype(np.uint8)
    img = Image.fromarray(rescaled)
    img.save(filename)
    files.download(filename)

def compare_methods(img_path, down_factor, up_factor, re_up_factor):
    img_array = get_img_array(img_path)

    # Downscaling results
    max_dn = max_downscale(img_array, down_factor)
    mean_dn = mean_downscale(img_array, down_factor)
    min_dn = min_downscale(img_array, down_factor)

    # Upscaling results (from Original)
    nn_up = nn_upscale(img_array, up_factor)
    bl_up = bilinear_upscale(img_array, up_factor)
    bc_up = bicubic_upscale(img_array, up_factor)

    # Upscaling from Mean Downscaled image (Reconstruction/Rescaling)
    nn_recon = nn_upscale(mean_dn, re_up_factor)
    bl_recon = bilinear_upscale(mean_dn, re_up_factor)
    bc_recon = bicubic_upscale(mean_dn, re_up_factor)

    # Visualization
    fig, axes = plt.subplots(3, 4, figsize=(20, 15))

    row1 = [("Original", img_array), ("Max Downscaling", max_dn), ("Average Downscaling", mean_dn), ("Min Downscaling", min_dn)]
    for i, (title, data) in enumerate(row1):
        axes[0, i].imshow(np.clip(data, 0, 255).astype(np.uint8))
        axes[0, i].set_title(f"{title}\n{data.shape[1]}x{data.shape[0]}")
        axes[0, i].axis('off')

    row2 = [("Original", img_array), ("Nearest Neighbor Upscaling", nn_up), ("Bilinear Upscaling", bl_up), ("Bicubic Upscaling", bc_up)]
    for i, (title, data) in enumerate(row2):
        axes[1, i].imshow(np.clip(data, 0, 255).astype(np.uint8))
        axes[1, i].set_title(f"{title}\n{data.shape[1]}x{data.shape[0]}")
        axes[1, i].axis('off')

    row3 = [("Mean Downscaling", mean_dn), ("Nearest Neighbor Rescaling", nn_recon), ("Bilinear Rescaling", bl_recon), ("Bicubic Rescaling", bc_recon)]
    for i, (title, data) in enumerate(row3):
        axes[2, i].imshow(np.clip(data, 0, 255).astype(np.uint8))
        axes[2, i].set_title(f"{title}\n{data.shape[1]}x{data.shape[0]}")
        axes[2, i].axis('off')

    plt.tight_layout()
    plt.show()

    # Downloads
    print("Starting downloads...")
    save_and_download(max_dn, "max_downscaled.jpg")
    save_and_download(mean_dn, "mean_downscaled.jpg")
    save_and_download(min_dn, "min_downscaled.jpg")
    save_and_download(nn_up, "nn_upscaled.jpg")
    save_and_download(bl_up, "bilinear_upscaled.jpg")
    save_and_download(bc_up, "bicubic_upscaled.jpg")
    save_and_download(nn_recon, "nn_reconstructed.jpg")
    save_and_download(bl_recon, "bilinear_reconstructed.jpg")
    save_and_download(bc_recon, "bicubic_reconstructed.jpg")

if 'fn' in locals():
    d_factor = int(input("Enter downscaling factor: "))
    u_factor = int(input("Enter upscaling factor: "))
    re_factor = int(input("Enter rescaling factor: "))
    compare_methods(fn, d_factor, u_factor, re_factor)

